using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WIndowsAuthCommon.Interfaces
{
    public interface ICustomUser : IBaseDBModel
    {
        string Id { get; set; }
        [Required]
        string UserName { get; set; }
        string FirstName { get; set; }

        string LastName { get; set; }

        [DataType(DataType.EmailAddress)]
        string Email { get; set; }

        [DataType(DataType.PhoneNumber)]
        string PhoneNumber { get; set; }

        string HashedPassword { get; set; }
        int PasswordIterationCount { get; set; }
        byte[] PasswordSalt { get; set; }

        bool IsUserAutoGenerated { get; set; }

    }
}
