namespace WIndowsAuthCommon.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class InitializeDB : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.IdentityRoles",
                c => new
                    {
                        Id = c.String(nullable: false, maxLength: 400),
                        Name = c.String(maxLength: 400),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IdentityUserRoles",
                c => new
                    {
                        RoleId = c.String(nullable: false, maxLength: 400),
                        UserId = c.String(nullable: false, maxLength: 400),
                        IdentityRole_Id = c.String(maxLength: 400),
                        CustomUser_Id = c.String(maxLength: 400),
                    })
                .PrimaryKey(t => new { t.RoleId, t.UserId })
                .ForeignKey("dbo.IdentityRoles", t => t.IdentityRole_Id)
                .ForeignKey("dbo.CustomUsers", t => t.CustomUser_Id)
                .Index(t => t.IdentityRole_Id)
                .Index(t => t.CustomUser_Id);
            
            CreateTable(
                "dbo.CustomUsers",
                c => new
                    {
                        Id = c.String(nullable: false, maxLength: 400),
                        FirstName = c.String(maxLength: 400),
                        LastName = c.String(maxLength: 400),
                        DateCreated = c.DateTime(nullable: false, precision: 7, storeType: "datetime2"),
                        DateLastModified = c.DateTime(nullable: false, precision: 7, storeType: "datetime2"),
                        HashedPassword = c.String(maxLength: 400),
                        PasswordIterationCount = c.Int(nullable: false),
                        PasswordSalt = c.Binary(),
                        IsUserAutoGenerated = c.Boolean(nullable: false),
                        Email = c.String(maxLength: 400),
                        EmailConfirmed = c.Boolean(nullable: false),
                        PasswordHash = c.String(maxLength: 400),
                        SecurityStamp = c.String(maxLength: 400),
                        PhoneNumber = c.String(maxLength: 400),
                        PhoneNumberConfirmed = c.Boolean(nullable: false),
                        TwoFactorEnabled = c.Boolean(nullable: false),
                        LockoutEndDateUtc = c.DateTime(precision: 7, storeType: "datetime2"),
                        LockoutEnabled = c.Boolean(nullable: false),
                        AccessFailedCount = c.Int(nullable: false),
                        UserName = c.String(maxLength: 400),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.IdentityUserClaims",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        UserId = c.String(maxLength: 400),
                        ClaimType = c.String(maxLength: 400),
                        ClaimValue = c.String(maxLength: 400),
                        CustomUser_Id = c.String(maxLength: 400),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.CustomUsers", t => t.CustomUser_Id)
                .Index(t => t.CustomUser_Id);
            
            CreateTable(
                "dbo.IdentityUserLogins",
                c => new
                    {
                        UserId = c.String(nullable: false, maxLength: 400),
                        LoginProvider = c.String(maxLength: 400),
                        ProviderKey = c.String(maxLength: 400),
                        CustomUser_Id = c.String(maxLength: 400),
                    })
                .PrimaryKey(t => t.UserId)
                .ForeignKey("dbo.CustomUsers", t => t.CustomUser_Id)
                .Index(t => t.CustomUser_Id);
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.IdentityUserRoles", "CustomUser_Id", "dbo.CustomUsers");
            DropForeignKey("dbo.IdentityUserLogins", "CustomUser_Id", "dbo.CustomUsers");
            DropForeignKey("dbo.IdentityUserClaims", "CustomUser_Id", "dbo.CustomUsers");
            DropForeignKey("dbo.IdentityUserRoles", "IdentityRole_Id", "dbo.IdentityRoles");
            DropIndex("dbo.IdentityUserLogins", new[] { "CustomUser_Id" });
            DropIndex("dbo.IdentityUserClaims", new[] { "CustomUser_Id" });
            DropIndex("dbo.IdentityUserRoles", new[] { "CustomUser_Id" });
            DropIndex("dbo.IdentityUserRoles", new[] { "IdentityRole_Id" });
            DropTable("dbo.IdentityUserLogins");
            DropTable("dbo.IdentityUserClaims");
            DropTable("dbo.CustomUsers");
            DropTable("dbo.IdentityUserRoles");
            DropTable("dbo.IdentityRoles");
        }
    }
}
